name: Gradle Check
on: [pull_request]

jobs:
  check:
    runs-on: self-hosted
    env:
      JAVA_HOME: /home/ubuntu/actions-runner/_work/_tool/Java_Adopt_jdk/14.0.2-12/x64
      JAVA11_HOME: /home/ubuntu/actions-runner/_work/_tool/Java_Adopt_jdk/11.0.13-8/x64/
      JAVA8_HOME: /home/ubuntu/actions-runner/_work/_tool/Java_Adopt_jdk/8.0.312-7/x64/
      JAVA14_HOME: /home/ubuntu/actions-runner/_work/_tool/Java_Adopt_jdk/14.0.2-12/x64
      JAVA17_HOME: /home/ubuntu/actions-runner/_work/_tool/Java_Adopt_jdk/17.0.1-12/x64
    strategy:
      fail-fast: false
      max-parallel: 4
    steps:
      - name: Checkout OpenSearch 
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          targets: 'JDK_8'
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          targets: 'JDK_11'
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          targets: 'JDK_17'
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '14'
          targets: 'JDK_14'
      
    

      # - uses: AdoptOpenJDK/install-jdk@v1
      #   id: setup-java-11
      #   with:
      #     version: '11'
      #     targets: 'JDK_11'

      # - uses: AdoptOpenJDK/install-jdk@v1
      #   with:
      #     version: '8'
      #     targets: 'JDK_8'

      # - uses: AdoptOpenJDK/install-jdk@v1
      #   with:
      #     version: '14'

      # - uses: AdoptOpenJDK/install-jdk@v1
      #   with:
      #     version: '17'
      #     targets: 'JDK_17'
      
      - name: Run env
        run: env
      # - name: Print jdk
      #   run: |
      #     echo "PRINT HERE"
      #     ls /opt/hostedtoolcache/Java_Adopt_jdk/14.0.2-12/


      - uses: gradle/gradle-build-action@v2
      - name: Run Gradle
        # run: |
        #   echo "./gradlew check --no-daemon --no-scan --parallel"
        #   ./gradlew check --no-daemon --no-scan --parallel
        #   GRADLE_CHECK_STATUS=$?

        #   if [ "$GRADLE_CHECK_STATUS" != 0 ]
        #   then
        #     echo Gradle Check Failed!
        #     exit $GRADLE_CHECK_STATUS
        #   fi
        run: ./gradlew check -PdisableBwcTest=true --parallel

      - name: Run BWC Test
        run: ./gradlew bwcTest

