name: Gradle Check
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '14', '17']
    env:
      JAVA_HOME: /usr/lib/jvm/adoptopenjdk-14-hotspot-amd64
      JAVA11_HOME: /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64
      JAVA8_HOME: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64
      JAVA14_HOME: /usr/lib/jvm/adoptopenjdk-14-hotspot-amd64
      JAVA17_HOME: /usr/lib/jvm/adoptopenjdk-17-hotspot-amd64

    name: Java ${{ matrix.Java }} sample
    steps:
      # - name: Checkout OpenSearch 
      #   uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
    

      # - uses: AdoptOpenJDK/install-jdk@v1
      #   id: setup-java-11
      #   with:
      #     version: '11'
      #     targets: 'JDK_11'

      # - uses: AdoptOpenJDK/install-jdk@v1
      #   with:
      #     version: '8'
      #     targets: 'JDK_8'

      # - uses: AdoptOpenJDK/install-jdk@v1
      #   with:
      #     version: '14'

      # - uses: AdoptOpenJDK/install-jdk@v1
      #   with:
      #     version: '17'
      #     targets: 'JDK_17'
      
      - name: Run env
        run: env
      - name: Print jdk
        run: |
          echo "PRINT HERE"
          ls -l /usr/lib/jvm/


      # - uses: actions/checkout@v2
      # - name: Run Gradle
      #   run: |
      #     echo "./gradlew check --no-daemon --no-scan --parallel"
      #     ./gradlew check --no-daemon --no-scan --parallel
      #     GRADLE_CHECK_STATUS=$?

      #     if [ "$GRADLE_CHECK_STATUS" != 0 ]
      #     then
      #       echo Gradle Check Failed!
      #       exit $GRADLE_CHECK_STATUS
      #     fi
